### ISSUE TITLE
[React New Frontend] Little Adjusts

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1118]
- [x] Job Result: some Headers are missing "Actions"? just write something about that
![image](https://user-images.githubusercontent.com/30625432/180418456-671097a7-b9bc-4048-ae43-9477f9ab9e24.png)

- [ ] check borders management (sometimes it overflows)
![image](https://user-images.githubusercontent.com/30625432/180419042-d19ec924-3f0e-461f-b477-2f51bcd63152.png)

- [x] remove "_" from job results like `reported_with_fails`

- [ ] if the logged in user is an admin, write it down here:
![image](https://user-images.githubusercontent.com/30625432/185340440-e197954a-eae2-44f9-97f8-e78c5b27d14f.png)

- [ ] dates regarding when an user joined an organization are not correctly shown in the GUI while in the DB are ok
![image](https://user-images.githubusercontent.com/30625432/209801742-6c9e2343-f923-40ad-8ab9-eb4329ddd643.png)

**Comment by mlodic** [comment]
"Actions"?

**Comment by taher-mulla** [comment]
Please assign this issue to me. I have a fix. But I do not have access to commit.

**Comment by mlodic** [comment]
hey yeah please open a PR with your changes :)

**Comment by AshirRashid** [comment]
I am unable to replicate the first issue (image below).
![CleanShot 2023-02-09 at 15 57 03](https://user-images.githubusercontent.com/64663586/217806425-72a4b9fb-a9d6-4191-876c-217ea24132a1.png)

The second and third bugs seem to have been fixed (image below).
![CleanShot 2023-02-09 at 15 55 42](https://user-images.githubusercontent.com/64663586/217806252-26f8f690-d82f-4733-b8f3-6697eee4dda6.png)

**Comment by mlodic** [comment]
the second bug has been partially addressed. There is still need to adjust the view of the MD5 field for instance.

The first bug has been partially addressed too. We could add something like "Details" as header in the first column.

**Comment by mlodic** [comment]
done
