### ISSUE TITLE
More robust testing for the REST API/ more testcases

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#229]
1. 1. [ ] Instead of manually defining the analyzer names like: [ref 1](https://github.com/intelowlproject/IntelOwl/blob/b8adb567171f6c59d5cf0dc8ca2c445af25191f4/tests/test_api.py#L145), [ref 2](https://github.com/intelowlproject/IntelOwl/blob/b8adb567171f6c59d5cf0dc8ca2c445af25191f4/tests/test_api.py#L78) - we can just pass `run_all_available_analyzers: true` in POST request body. (_not sure, might change this_)
2. 2. [ ] Currently, the `script_analyzers.general.start_analyzers` function is not called during tests. This really decreases the overall code coverage and also misses out on spotting many errors especially those that have to do with some typo or mistake in the analyzer_config entries. So, we should make changes in a way that detects such errors too.
3. 3. [x] Add `codecov` ([ref](https://docs.codecov.io/docs/python)) support to the GitHub actions and for [pull requests](https://docs.codecov.io/docs/pull-request-comments) too. (PR: #305)
4. 4. [x] Need to add tests for the `/api/jobs` , `/api/jobs/{id}` (GET) and `/api/tags`, `/api/tags/{id}` (GET, POST, PUT, DELETE) endpoints inside [`tests/test_api.py` ](https://github.com/intelowlproject/IntelOwl/blob/master/tests/test_api.py): `ApiTests` class. Refer [here](https://www.django-rest-framework.org/api-guide/testing/). (PR: #317)
5. 5. [ ] It would also be really good if we are able to add tests for verifying permissions/groups. For example, enabling/disabling certain permissions to a group/user and then making request to a protected endpoint and verify that the behavior changed.
6. 6. [x] Add tests for `DELETE /api/jobs/{id}`, `PATCH /api/jobs/{id}/kill`, `GET /api/get_analyzer_configs` and `GET /api/download_sample` endpoints as well. (PR: #317)

**Comment by mlodic** [comment]
We could take this chance to add a code coverage linter for CI to evaluate how much our tests are good

**Comment by m0mosenpai** [comment]
I would like to work on this. Things to keep in mind/ starting suggestions would be great if possible.

**Comment by Eshaan7** [comment]
@m0mosenpai,
- Need to add tests for the `/api/jobs` and `/api/tags` endpoints inside [`tests/test_api.py` ](https://github.com/intelowlproject/IntelOwl/blob/master/tests/test_api.py): `ApiTests` class. Refer [here](https://www.django-rest-framework.org/api-guide/testing/)
- Add `codecov` ([ref](https://docs.codecov.io/docs/python) support to the GitHub actions and for [pull requests](https://docs.codecov.io/docs/pull-request-comments) too.

**Comment by Eshaan7** [comment]
@m0mosenpai, in order of priority,
- Point 3
- Point 4
- Point 2
- Point 5

**Comment by mlodic** [comment]
I write this consideration here because it seems pertinent to next developments related to this issue. 

About #305, I would like to remove the dependency from `django_nose`. I did not notice earlier but this is an old library and they explicitly state that it should not be used for new projects: 

>  New projects should consider using pytest, or unittest with the Django testing framework.

Could you explain me what is the purpose of this library?

**Comment by m0mosenpai** [comment]
From what I understood, nose is just being used to run the tests and generate the coverage report for codecov.io. It supports direct arguments for coverage report generation and might just be a convenient way of achieving this. I do remember seeing `pytest-cov` package to get coverage reports via `pytest` instead. I think that could be used as replacement for `nose`. 

Also, as for the error, I think it might be due to some issue nose has with running test functions directly (not via calling the class). Now that I think about it, I do remember using one of the `FileAnalyzers...` classes to test the coverage reports and might have missed this error due to that. Sorry about that. I'm not completely sure if this is the reason though.

I can work on replacing it with `pytest` and `pytest-cov`. @Eshaan7 correct me if i'm wrong here/ any other suggestions please.

**Comment by Eshaan7** [comment]
> Also, this library breaks the execution of tests manually.

I think those would have to be executed via `nosetests tests.test_generic:CronTests.test_maxmind_updater`.

> I did not notice earlier but this is an old library and they explicitly state that it should not be used for new projects:

yes, I did not notice that either but it worked for me well in the django-durin package and that is why I recommended @m0mosenpai to use `django-nose`.

django-nose is in maintenance mode, it's not dead yet so we can work on migrating to pytest or unittests with low priority IMHO.

**Comment by mlodic** [comment]
that command does not work to me. Is that written somewhere in the `django-nose` docs? (I did not find anything)

I think that `manage.py` cannot be avoided to use the Django environment properly.

If we can run the testing suite normally, I agree that we can keep it but we should update the `Tests` sections of the docs. 

Otherwise we have to remove it.

**Comment by Eshaan7** [comment]
I agree. Can you try this once ?

```bash
docker exec -ti intel_owl_uwsgi python3 manage.py test tests.test_generic:CronTests.test_maxmind_updater
```

**Comment by mlodic** [comment]
Sorry for the delay of my response, but yes that works! Great, I have just updated the docs. So `:` must be added after the module name, is this the rule?

**Comment by m0mosenpai** [comment]
I think that's right. It says the same in the accepted answer and comments in this post as well -
`A colon separates the module file path and the objects within that file`
https://stackoverflow.com/questions/3704473/how-do-i-run-a-single-test-with-nose-in-pylons

**Comment by Eshaan7** [comment]
Sorry, @mlodic. Actually, I reopen this because we still have some checkboxes/todos left on this issue if you see in the original post.

**Comment by mlodic** [comment]
yes it was autoclosed because linked to a PR
