### ISSUE TITLE
Start with --traefik option

### ISSUE THREAD

**Issue by agnorance** [intelowlproject/IntelOwl#2305]
## What happened
I wanted to start your awesome project with traefik as the respective proxy, but got an error message indicating the --traefik option isn't known. 

## Environment
1. OS: Ubuntu
2. IntelOwl version: Latest

##  What did you expect to happen
I expect to have an additional container with traefik. 

## How to reproduce your issue
Clone project. Let ```./initialize.sh``` run. Run:

```
# From your --help
start <env> <command> [OPTIONS]

ubuntu@intelowl:~/IntelOwl$ ./start prod up --traefik
```

## Error messages and logs
Error! Invalid option --traefik.

**Comment by agnorance** [comment]
Moved to discussions.

**Comment by fgibertoni** [comment]
Hello @agnorance, thank you for reaching out! :)
I should have fixed the issue in #2307. 
Can you try it to see if it works for you ?

**Comment by agnorance** [comment]
Hello @fgibertoni 

Thanks for you quick response. 

Do I have to run it from a different branch or is it already merged?

**Comment by agnorance** [comment]
I also have a different problem: 

```
ubuntu@intelowl:~/IntelOwl$ ./start prod up --traefik
WARN[0000] /home/ubuntu/IntelOwl/docker/default.yml: `version` is obsolete 
WARN[0000] /home/ubuntu/IntelOwl/docker/postgres.override.yml: `version` is obsolete 
WARN[0000] /home/ubuntu/IntelOwl/docker/redis.override.yml: `version` is obsolete 
WARN[0000] /home/ubuntu/IntelOwl/docker/traefik.override.yml: `version` is obsolete 
WARN[0000] The "c" variable is not set. Defaulting to a blank string. 
WARN[0000] The "c" variable is not set. Defaulting to a blank string. 
WARN[0000] The "c" variable is not set. Defaulting to a blank string. 
WARN[0000] The "c" variable is not set. Defaulting to a blank string. 
unable to get image 'intelowlproject/intelowl_nginx:"v6.0.2"': Error response from daemon: invalid reference format
```

Do you know this problem? 


Kind regards,
agnorance

**Comment by mlodic** [comment]
I have just pushed a new version. Please pull from the `master` branch and try again

**Comment by agnorance** [comment]
Hello @mlodic 

I still get the same error: 

```
ubuntu@intelowl:~/IntelOwl$ ./start prod up --traefik

WARN[0000] /home/ubuntu/IntelOwl/docker/default.yml: `version` is obsolete 
WARN[0000] /home/ubuntu/IntelOwl/docker/postgres.override.yml: `version` is obsolete 
WARN[0000] /home/ubuntu/IntelOwl/docker/redis.override.yml: `version` is obsolete 
WARN[0000] /home/ubuntu/IntelOwl/docker/traefik.override.yml: `version` is obsolete 
unable to get image 'intelowlproject/intelowl_nginx:"v6.0.2"': Error response from daemon: invalid reference format
```

I have deleted the old clone and cloned the repo again, configured it according to the documentation. 

It seems as if the ```${REACT_APP_INTELOWL_VERSION}``` variable gets populated incorrectly with "": 

```
# this:
intelowlproject/intelowl_nginx:"v6.0.2"'

# ...should probably be:
intelowlproject/intelowl_nginx:v6.0.2

# ...or even:
intelowlproject/intelowl_nginx:6.0.2
```

Kind regards

**Comment by mlodic** [comment]
That's strange cause I can't replicate that issue. Anyway I am happy you managed to run the application

**Comment by switch-csoc** [comment]
Hey @mlodic 

I was able to get it running using the newest version of traefik 3.0. 

Now, there was a bit of a hassle with getting everything on the same network and I also had to change some configuration regarding the ports used (nginx container). 

Before I put the effort in and create a merge request and stuff: Would you even be interested in such an addition? 

Kind regards

**Comment by agnorance** [comment]
Hey @mlodic 

I was able to get it running using the newest version of traefik 3.0.

Now, there was a bit of a hassle with getting everything on the same network and I also had to change some configuration regarding the ports used (nginx container).

Before I put the effort in and create a merge request and stuff: Would you even be interested in such an addition?

I think it would be really cool addition, as traefik allows for very easy setup and for example ip-based access control like this: 

```
- "traefik.http.routers.nginx.middlewares=nginx-ipallowlist"
- "traefik.http.middlewares.nginx-ipallowlist.ipallowlist.sourcerange=<IP>" 
```

Kind regards

**Comment by mlodic** [comment]
sure! that would be really cool! feel free to open a PR, we'll review it and help!
