### ISSUE TITLE
[docs] Proper API specs/docs using Swagger

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/IntelOwl#323]
- Writing proper documentation for the API endpoint functions (_api_app/api.py_)
> Need to use proper syntax as given [here](https://drf-yasg.readthedocs.io/en/1.0.4/custom_spec.html).
_Originally posted by @Eshaan7 in https://github.com/intelowlproject/IntelOwl/pull/344#issuecomment-786725761_
- Using https://www.django-rest-framework.org/topics/documenting-your-api/ to generate docs and API specs
- Use [this](https://drf-yasg.readthedocs.io/en/stable/rendering.html#management-command) to create the spec file, and then use the `sphinx-redoc` extension to generate redoc along with rest of the docs. Then link both docs together with [something like this](https://github.com/sphinx-contrib/redoc/issues/15). There should be a GH workflow setup for this.

**Comment by spiderxm** [comment]
assign me this issue

**Comment by Purhan** [comment]
It's been a while since this was assigned to someone. I'd like to work on this if it's open for contribution!

**Comment by mlodic** [comment]
hey @Purhan thank you for your interest in the project! You have been assigned

**Comment by Purhan** [comment]
@mlodic Thanks for assigning! I have created a PR. Review will be appreciated.

**Comment by CITIZENDOT** [comment]
> Also I think we should rewrite the docstrings of the APIs because swagger cannot parse that data correctly.

Yes, it's our mistake for not following a proper syntax while writing doc strings.

Need to use proper syntax as given [here](https://drf-yasg.readthedocs.io/en/1.0.4/custom_spec.html).
> descriptions for Operations, Parameters and Schemas are picked up from docstrings and help_text attributes in the same manner as the default DRF SchemaGenerator

_Originally posted by @Eshaan7 in https://github.com/intelowlproject/IntelOwl/issues/344#issuecomment-786725761_

So, Before diving into swagger, We have to fix doc strings, Right? Let me do that then.

**Comment by mlodic** [comment]
solved with #417

**Comment by Eshaan7** [comment]
The automation part of this issue still needs to be done. (could use https://github.com/NiklasRosenstein/readthedocs-custom-steps/)

**Comment by uzair-ali10** [comment]
Hey, can anyone clarify what part of this issue is solved and what needs to be implemented more?

**Comment by fear-the-reaper** [comment]
Hello! Is this issue still open? If so can you clarify what needs to be done? Thanks!

**Comment by mlodic** [comment]
Honestly I did not understand what @eshaan7 meant by that. I guess this could be closed

**Comment by eshaan7** [comment]
The [schema.yml](https://github.com/intelowlproject/IntelOwl/blob/master/docs/source/schema.yml) file is not automatically updated and we need a GitHub action to manage this. (As you can see even right now, the schema.yml file says the version is 3.1.0 even though we are on 3.3.0)

This workflow could be made part of the existing [sphinx_build_on_release.yml](https://github.com/intelowlproject/IntelOwl/blob/master/.github/workflows/sphinx_build_on_release.yml) file.

**Comment by mlodic** [comment]
superseded by #2043
